prediction_image_dir = '/home/korbinian/Desktop/Datasets_v2/real/predictions/resnet50_csv_03.h5/images/'
prediction_label_dir = '/home/korbinian/Desktop/Datasets_v2/real/predictions/resnet50_csv_03.h5/labels'
input_image_dir = '/home/korbinian/Desktop/testsets/testset_easy/images/'
ground_truth_label_dir = '/home/korbinian/Desktop/testsets/testset_easy/labels/'
weights_file = '/home/korbinian/Desktop/Datasets_v2/real/snapshots/resnet50_csv_03.h5'
